# Generated by Django 5.2.17 on 2026-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descripcion',
            field=models.CharField(default='Soy un servicio', max_length=100),
        ),
    ]
