# Generated by Django 5.2.17 on 2026-10-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descripcion',
            new_name='description',
        ),
    ]
